### ISSUE TITLE
`crypto/secp256k1` toplama, çarpma, `double()` yordamlarını test edelim

### ISSUE THREAD

**Issue by mnsaglam** [KimlikDAO/kimlikdao-js#7]
Toplama çarpma ve `double()` yordamlarını in-place hale getirdik. Böylece yeni allocation olmadan bir çok işlemi yapabiliyoruz. Bu methodları test edelim. Noble'ın implementation'u ile karşılaştirarak ve ya matematiksel olarak hesapladığımiz invariant'lari kontrol ederek.

- [x] toplama testleri
- [x] `double()` testleri
- [x] çarpma testleri

**Comment by 0x471** [comment]
Toplama ve double testleri eklendi: https://github.com/KimlikDAO/kimlikdao-js/commit/9886f1c794132d4994b57e08113ca68723545d54

`Multiply()` fonksiyonu girilen değer fark etmeksizin `x: 0, y: 0, z: 1` döndürüyor.
