### ISSUE TITLE
`README.md` dosyası oluşturup kimlikdao-js tanıtımı yazalım

### ISSUE THREAD

**Issue by mnsaglam** [KimlikDAO/kimlikdao-js#8]
Türkçe olarak kimlikdao-js in kısa açıklaması olsun.

- [x] Repo nasıl klonlanır
- [x] Testler nasıl çalıştiılır
- [x] Compiled test nedir vitest nedir

Klasörlerde neler var, yeni modüller nereye gitmeli

**Comment by 0x471** [comment]
Commit: https://github.com/KimlikDAO/kimlikdao-js/commit/b58484ad12a4e6e7c4d69933798ba23f466dd2d2

**Comment by 0x471** [comment]
https://github.com/KimlikDAO/kimlikdao-js/commit/4e47458df6b2855284c772f9e5b3e77d133930a8
